[build]
  base = "frontend/school-frontend-app"
  publish = "build"
  command = "npm install --legacy-peer-deps && node scripts/simple-build.js"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-optional"
  NETLIFY_USE_YARN = "false"
  NODE_OPTIONS = "--max-old-space-size=1536"

# Handle OPTIONS requests for CORS preflight
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/options"
  status = 200
  force = true
  conditions = {Method = ["OPTIONS"]}

# Handle login requests
[[redirects]]
  from = "/api/users/login"
  to = "/.netlify/functions/mock-login"
  status = 200
  force = true

# Handle all other API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/simple-proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
