[build]
  base = "frontend/school-frontend-app"
  publish = "build"
  command = "npm ci && npm run build"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "16"
  NPM_FLAGS = "--no-optional"
  NETLIFY_NEXT_CACHE_HANDLER = "false"
  NETLIFY_CACHE_BUST = "${new Date().getTime()}"

[[plugins]]
  package = "./netlify/plugins/clear-cache"

[dev]
  functions = "netlify/functions"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
