[build]
  base = "frontend/school-frontend-app"
  publish = "build"
  command = "npm install --legacy-peer-deps && node scripts/use-simple-eslint.js && node scripts/fix-eslint-errors.js && DISABLE_ESLINT_PLUGIN=true ESLINT_NO_DEV_ERRORS=true CI= npm run build"

# Handle OPTIONS requests for CORS preflight
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/options"
  status = 200
  force = true
  conditions = {Method = ["OPTIONS"]}

# Handle all other API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
