[build]
  base = "frontend/school-frontend-app"
  publish = "build"
  command = "npm install --legacy-peer-deps && node scripts/use-simple-eslint.js && node scripts/fix-eslint-errors.js && node scripts/modify-api-service.js && node scripts/force-relative-url.js && node scripts/patch-login.js && DISABLE_ESLINT_PLUGIN=true ESLINT_NO_DEV_ERRORS=true REACT_APP_USE_PROXY=true REACT_APP_API_URL=/api CI= npm run build"

# Handle OPTIONS requests for CORS preflight
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/options"
  status = 200
  force = true
  conditions = {Method = ["OPTIONS"]}

# Handle login requests
[[redirects]]
  from = "/api/users/login"
  to = "/.netlify/functions/mock-login"
  status = 200
  force = true

# Handle all other API requests
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/simple-proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
