[build]
  publish = "build"
  command = "npm run build:netlify"

[build.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://agape-seminary-school.onrender.com/api"
  REACT_APP_USE_MOCK_DATA = "false"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
